# Generated by Django 4.1.7 on 2023-02-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
